### ISSUE TITLE
What @ref and @li mean?

### ISSUE THREAD

**Issue by 1c7** [rambodrahmani/ffmpeg-video-player#2]
## For example `tutorial01/tutorial01.c`
![image](https://user-images.githubusercontent.com/1804755/96966122-decc8380-153f-11eb-8fd7-9ebba258e93f.png)

## What's their meaning?

**Comment by ghost** [comment]
I really don't know to be honest. I mean, I started coding using the CLion IDE. I believe those are notations introduced by CLion automatically. Maybe, @li = list item, and @ref = external reference.

**Comment by 1c7** [comment]
Understood, Thank you!

**Comment by 1c7** [comment]
### Can I delete every `@li` and `@ref` and send a Pull Request?
since they are useless and confuse other people who are reading this
