### ISSUE TITLE
SDL_CreateWindow should move into main thread

### ISSUE THREAD

**Issue by everywill** [rambodrahmani/ffmpeg-video-player#7]

**Comment by FlexW** [comment]
Not only `SDL_CreateWindow`, but also `SDL_CreateRenderer()` and `SDL_CreateTexture()`. Otherwise, no picture will show up for me.

**Comment by zacgibson21** [comment]
> Not only `SDL_CreateWindow`, but also `SDL_CreateRenderer()` and `SDL_CreateTexture()`. Otherwise, no picture will show up for me.

@FlexW I think I am having the same issue, starting from tutorial_04 I cannot get an image to display. Were you able to get these calls moved the the main thread? If so would you mind sharing your changes? 

Thank you!

**Comment by FlexW** [comment]
@zacgibson21 Yes, I will later this day create a pull request.

**Comment by FlexW** [comment]
@zacgibson21 I opened a PR. You can see the changes that I made there.
